---
title: "Scraper Example"
output: html_document
---

```{r setup, include=FALSE}

#install.packages('rvest')
library(rvest)
```

### web-scaraper for news site
css-selectors: https://www.w3schools.com/cssref/css_selectors.asp

```{r get}
url <- "http://news.liga.net/all/"
content <- read_html(url)


### Title
# 1st attempt
content %>% html_nodes('li div.title a') %>% html_text()

# 2st attempt
content %>% html_nodes('li div.title a:first-child') %>% html_text()

title <- content %>% html_nodes('div.articles-list li div.title a:first-child') %>% html_text()

### Link to article
# g! rvest href attribute
link <- content %>% html_nodes('li div.title a:first-child') %>% html_attr('href')



### Time
content %>% html_nodes('li div.date a:first-child') %>% html_text() #nothing
content %>% html_nodes('li div.date') %>% html_text() # almost
content %>% html_nodes('div.articles-list li div.date') %>% html_text() # yep!

time <- content %>% html_nodes('div.articles-list li div.date') %>% html_text() 
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
