---
title: "Фінальний проект"
output: html_notebook
---


Ваша задача - проаналізувати набір даних про затримки літаків.

Вам потрібно буде:
1. Визначити питання, на яке потрібно буде знайти відповідь за допомогою аналізу
2. Написати R notebook з текстом та кодом аналізу, з використанням dplyr та ggplot2.

Можливі варіанти тем: 
- Як залежить затримка літаків від часових параметрів? (час доби, день тижня, місяць)
- Як залежить затримка від погодних умов в аеропортах вильоту/прильоту?
- Як залежить затримка від місця розташування (тут доречна карта з усіма аеропортами) або від інших параметрів аеропортів (наприклад, розміру)
- Як залежить затримка від типів літаків, авіаліній? 
- Чи справді перелетіти через Атлантику важче з США в Європу, ніж з Європи в США або вздовж американського континенту?
- ... інша ваша тема по цим даним

Запрошую вас активно задавати питання у нашому (slack-каналі)[https://ucudata.slack.com/messages], у тому числі і на етапі вибору теми 


```{r}
library(nycflights13)
data(package = "nycflights13")

```

Максимальна оцінка за фінальний проект - 35 балів. Якщо теми досліджень будуть співпадати, кожен наступний проект після першого отримає на 10 балів менше.


### Трохи формальностей: як я буду оцінювати ваші результати?  
  * Якщо ви хоча б частково ходили на заняття, це 30 балів
  * За перше завдання - 10 балів
  * За друге завдання - 25 балів (пункт 2 - 15 балів, пункт 3 - 10 балів, пункт перший можна не робити через непрацюючий сайт. Для другого пункту на github є набір даних pid_kupolom.csv).
  * За фінальний проект, як я вже сказав - 35 балів
